### ISSUE TITLE
cant deploy on vercel

### ISSUE THREAD

**Issue by SolimanFG** [colbyfayock/meme-generator#1]

**Comment by colbyfayock** [comment]
hey i just gave it a try on a new project and didnt seem to have any issues. did you configure your environment variables? not sure if it's needed for deployment but worth checking

<img width="1363" alt="image" src="https://github.com/colbyfayock/meme-generator/assets/1045274/bb9009bc-3277-4028-b388-cdb5594cb5a2">

**Comment by MeliodaZ1** [comment]
hey man , sorry i tried again it gave me the error again i dont know how to create it . :(

**Comment by MeliodaZ1** [comment]
> hey i just gave it a try on a new project and didnt seem to have any issues. did you configure your environment variables? not sure if it's needed for deployment but worth checking
> 
> <img alt="image" width="1363" src="https://private-user-images.githubusercontent.com/1045274/323254424-bb9009bc-3277-4028-b388-cdb5594cb5a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjY0MDksIm5iZiI6MTcxMzM2NjEwOSwicGF0aCI6Ii8xMDQ1Mjc0LzMyMzI1NDQyNC1iYjkwMDliYy0zMjc3LTQwMjgtYjM4OC1jZGI1NTk0Y2I1YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMTUwMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAzYmJjOWFiNDQ1NzMwZjhhMTg5NDAxNWFmNjQxODYyODRkZjhhOTU2ZmM1NzVjNDJkMmJkYTA5OGU1Zjk1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N9_mghgiBVBqvWZkR06jLdZ8S_JF5Em27RmNLBZ1Bfs">

can i have this please ?

**Comment by colbyfayock** [comment]
Do you mean the environment variables? Those would come from your own Cloudinary account
